env:
# Specify the main Mafile supported goals.
  - GOAL=test
  - GOAL=targets-group-1
  - GOAL=targets-group-2
  - GOAL=targets-group-3
  - GOAL=targets-group-4
  - GOAL=targets-group-5
  - GOAL=targets-group-6
  - GOAL=targets-group-7
  - GOAL=targets-group-8
  - GOAL=targets-group-rest

# use new docker environment
sudo: false

git:
  depth: 5

addons:
  apt:
    packages:
      - build-essential
      - git
      - libc6-i386
      - time

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

before_install:

install:
  - make arm_sdk_install

before_script:
  - make arm_sdk_version
  - clang --version
  - clang++ --version

script: ./.travis.sh

cache: 
  timeout: 1000
  directories:
  - downloads
  - tools

notifications:
  #slack: inavflight:UWRoWFJ4cbbpHXT8HJJlAPXa
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/34e795df229478ac3a3b
    on_success: always
    on_failure: always
    on_start: never
